services:
  rabbitmq:
    image: rabbitmq:4.0.2-management
    container_name: rabbiqmq
    ports:
        - 5672:5672
        - 15672:15672

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
        - 1433:1433
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=todo@db2024
        - MSSQL_PID=Express

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
        - 27017:27017
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root

  elasticsearch:
    image: elasticsearch:8.15.3    
    container_name: elasticsearch
    ports: 
        - 9200:9200
    volumes:
        - es_data:/usr/share/elasticsearch/data
    environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - ES_JAVA_OPTS=-Xms512m -Xmx512m

  kibana:
    image: kibana:8.15.3
    container_name: kibana
    environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
        - 5601:5601

volumes:
  es_data:
    driver: local
  
    